/**
 * Drop the SSR documents that a deploy left behind.
 *
 * The document embeds Vite's content-hashed asset URLs, so a cached copy that
 * outlives its build names `/assets/*` files that no longer exist and the page
 * renders nothing but its loading spinner. `cross_version_cache: false`
 * (wrangler.jsonc) is supposed to make that impossible: cache keys include the
 * Worker version, so a deploy starts cold.
 *
 * Measured 2026-08-15, it is *nearly* true. Version `93ad4084` was created at
 * 12:06:20 UTC; the poisoned entry being served three minutes later had been
 * written at 12:06:21 UTC — one second after the flip, not before it. It was not
 * an entry that survived the deploy, it was one *created during* it: a response
 * generated by the outgoing version whose cache write landed in the incoming
 * version's namespace. Version keying starts a deploy cold; it does not cover
 * the second or two either side of the flip. One entry per deploy per colo, and
 * `s-maxage=3600` pinned it there for an hour.
 *
 * So the `html` tag stops being purely an escape hatch. The cron already runs
 * every ten minutes and already knows how to purge; all it lacked was any way to
 * know a deploy had happened. The `version_metadata` binding supplies exactly
 * that, and it needs no stored state to interpret — the version's own upload
 * timestamp is the signal.
 */
import { parseAbsolute, type ZonedDateTime } from '@internationalized/date';
import { DOCUMENT_TAG } from '@/server/cache-headers';
import { resolvePurgeTarget } from '@/server/purge';

/**
 * The cron interval, which must match `triggers.crons` in wrangler.jsonc. Same
 * arrangement as YEAR_CACHE_TIERS in @/shared/config, which the refresher reads
 * as a write schedule: one definition, so the schedule and the code that reasons
 * about it cannot disagree.
 */
export const CRON_INTERVAL_SECONDS = 600;

/**
 * How young a version has to be for its deploy to still be worth purging after.
 *
 * Two intervals, not one, and the extra one is the whole point. The poisoning
 * write lands a second or so *after* the version flip, so a tick that happens to
 * fire in that same second would purge and then be re-poisoned. The second tick
 * is the one guaranteed to run after the race is over. The cost is at most two
 * purge calls per deploy, against this zone's Free-plan ceiling of five a
 * minute — and a purge is cheap here, because R2 sits under the cache and never
 * expires, so the next reader pays an R2 read rather than an OpenElectricity
 * fetch.
 */
export const PURGE_WINDOW_SECONDS = CRON_INTERVAL_SECONDS * 2;

/**
 * How long ago this Worker version was uploaded, in seconds, or null if the
 * timestamp cannot be read.
 *
 * `parseAbsolute` rather than `new Date`: the house rule is @internationalized/
 * date, and the boundary this crosses is an ISO-8601 string from Cloudflare's
 * control plane, not a date of ours.
 */
export function versionAgeSeconds(
  versionTimestamp: string,
  at: ZonedDateTime,
): number | null {
  let uploadedAt: ZonedDateTime;
  try {
    uploadedAt = parseAbsolute(versionTimestamp, 'UTC');
  } catch {
    return null;
  }
  return (at.toDate().getTime() - uploadedAt.toDate().getTime()) / 1000;
}

/**
 * Did we deploy recently enough that the edge may be holding a document from
 * the build before this one?
 *
 * Fails CLOSED on anything it cannot make sense of — an unparseable timestamp,
 * or a version that claims to be from the future (clock skew). The alternative
 * is a cron that purges every tick forever, which would quietly turn the
 * document cache off rather than fix it.
 */
export function shouldPurgeDocuments(
  versionTimestamp: string,
  at: ZonedDateTime,
): boolean {
  const age = versionAgeSeconds(versionTimestamp, at);
  if (age === null) return false;
  return age >= 0 && age <= PURGE_WINDOW_SECONDS;
}

export interface DeployPurgeResult {
  purged: boolean;
  ageSeconds: number | null;
}

/**
 * Called from `scheduled` on every tick; does nothing on all but the one or two
 * that follow a deploy.
 *
 * Logged either way, and with the age rather than just the decision, because
 * the question a tail needs to answer is "did the purge fire, and how long after
 * the deploy?" — which a bare "purged: false" cannot.
 */
export async function purgeDocumentsAfterDeploy(
  version: WorkerVersionMetadata | undefined,
  at: ZonedDateTime,
  from?: CacheContext,
): Promise<DeployPurgeResult> {
  if (!version) {
    console.log(JSON.stringify({ log: 'deploy-purge', reason: 'no-version-binding' }));
    return { purged: false, ageSeconds: null };
  }

  const ageSeconds = versionAgeSeconds(version.timestamp, at);
  if (!shouldPurgeDocuments(version.timestamp, at)) {
    return { purged: false, ageSeconds };
  }

  const target = resolvePurgeTarget(from);
  if (!target) {
    console.log(JSON.stringify({ log: 'deploy-purge', reason: 'purge-unavailable' }));
    return { purged: false, ageSeconds };
  }

  try {
    const result = await target.purge({ tags: [DOCUMENT_TAG] });
    console.log(JSON.stringify({
      log: 'deploy-purge',
      versionId: version.id,
      ageSeconds: Math.round(ageSeconds ?? 0),
      purged: result.success,
      errors: result.success ? undefined : result.errors,
    }));
    return { purged: result.success, ageSeconds };
  } catch (error) {
    console.error(JSON.stringify({
      log: 'deploy-purge:failed',
      versionId: version.id,
      error: error instanceof Error ? error.message : String(error),
    }));
    return { purged: false, ageSeconds };
  }
}
